import { useQuery } from 'react-query';
import { getApiClient } from 'src/helpers/apiConfig';
// Generated by https://quicktype.io

export interface IntegrationProviders {
  message: string;
  data: Datum[];
}

export interface Datum {
  id: string;
  name: string;
  icon: string;
  connects_with: string[];
  created_at: string;
  updated_at: string;
}

const useGetIntegrationProviders = () => {
  return useQuery('integrationProviders', async () => {
    return getApiClient().get<IntegrationProviders>('/integrations/providers');
  });
};

export default useGetIntegrationProviders;
