import { useQuery } from 'react-query';
import { getApiClient } from 'src/helpers/apiConfig';

// Generated by https://quicktype.io

export interface ActivatedIntegrations {
  message: string;
  data: Datum[];
}

export interface Datum {
  id: string;
  integration_name: string;
  provider_id: string;
  company_id: string;
  user_id: string;
  connection_data: ConnectionDatum[];
  created_at: string;
  updated_at: string;
  provider: Provider;
  user: User;
}

export interface ConnectionDatum {
  name: string;
  value: string;
}

export interface Provider {
  id: string;
  name: string;
  icon: string;
  connects_with: string[];
  created_at: string;
  updated_at: string;
}

export interface User {
  id: string;
  first_name: string;
  last_name: string;
  email: string;
  password: string;
  role: string;
  company_id: string;
  company_role: null | string;
  created_at: string;
  updated_at: string;
}

const useGetActivatedIntegrations = () => {
  return useQuery('activatedIntegration', async () => {
    return getApiClient().get<ActivatedIntegrations>(
      '/integrations/provider/activated'
    );
  });
};

export default useGetActivatedIntegrations;
