export const companyRoles = [
  'CEO',
  'CTO',
  'CFO',
  'CMO',
  'Developer',
  'Analyst',
  'Data Engineer',
];

export const companySizes = ['1-9', '10-49', '50-249', '250+'];

export const industries = [
  'Agency',
  'Adtech',
  'Aerospace',
  'Agriculture',
  'Analytics',
  'B2B SaaS',
  'Biotech',
  'Community',
  'Construction',
  'Consumer',
  'Developer Tools',
  'Ecommerce/Retail',
  'Energy',
  'Enterprise',
  'Entertainment',
  'Education',
  'Financial Services',
  'Food/Beverage',
  'Freight',
  'Gaming',
  'Hardware',
  'Healthcare',
  'Insurance',
  'Marketplace',
  'Media',
  'Real Estate',
  'Transportation',
  'Other',
];
