import Head from 'next/head';
import styles from 'src/styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          <a className={styles.card} href="">
            <h2>Orders</h2>
            <p>Total number of orders</p>
          </a>

          <a className={styles.card} href="">
            <h2>Gross revenue</h2>
            <p>The total price of all items in Orders</p>
          </a>

          <a className={styles.card} href="">
            <h2>Discount</h2>
            <p>The best way to define discount is to multiply t...</p>
          </a>

          <a className={styles.card} href="">
            <h2>Average sale amount</h2>
            <p>The average price of or...</p>
          </a>

          <a className={styles.card} href="">
            <h2>Units sold</h2>
            <p>Total quantity of orders</p>
          </a>

          <a className={styles.card} href="">
            <h2>Net revenue</h2>
            <p>Gross revenue excluding Discount</p>
          </a>
          <a className={styles.card} href="">
            <h2>Cost of goods sold</h2>
            <p>Total price of item, rem...</p>
          </a>
          <a className={styles.card} href="">
            <h2>Gross profit amount</h2>
            <p>Net revenue excluding ...</p>
          </a>
          <a className={styles.card} href="">
            <h2>Gross profit margin</h2>
            <p>Gross profit amount div...</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer} />
    </div>
  );
}
