import Image from 'next/image';

import styles from './metricPopup.module.css';

type MetricPopupProps = {
  onClose: () => void;
};

const MetricPopup = ({ onClose }: MetricPopupProps) => {
  return (
    <div
      className={`${styles.popupWrapper} p-4 border border-primary rounded-lg mb-4 flex gap-8 items-start justify-between`}
    >
      <div className="flex items-center gap-4">
        <Image alt="magic" height="32" src="/icons/icon-magic.svg" width="32" />
        <div className="text-['#1A202C']">
          <p className="font-semibold mb-1">
            We’ve autogenerated these metrics based on your data.
          </p>
          <p>
            Now it’s your turn to customize them. Edit your definitions in line
            with how your company does things to get the best results.
          </p>
        </div>
      </div>
      <button className="cursor-pointer" onClick={onClose} type="button">
        <Image alt="close" height="24" src="/icons/icon-x.svg" width="24" />
      </button>
    </div>
  );
};

export default MetricPopup;
